class Emojis:
    CROSS = "❌"
    CHECK = "✅"
    SEARCH = "🔎"
    GREEN_DOT = "🟢"
    LINK = "🔗"
    LOCK = "🔐"
    SETTINGS = "⚙️"
    CASH_BAG = "💰"
    CREDIT_CARD = "💳"
    CLOCK = "🕦"
    IMAGE = "🖼"
    MESSAGE = "💬"
    GROUP = "👥"
    GRAPH = "📊"
    PACKAGE = "📦"
